definitions:
  environment_versions: &hello_environment_versions
    xcode: 13.3
    vars:
      XCODE_PROJECT: "HELLO WORLD.xcodeproj"
      XCODE_iOS_SCHEME: "HELLO WORLD"

workflows:
  ios-testing-workflow:
    name: iOS Testing Workflow
    instance_type: mac_mini_m1
    environment:
      <<: *hello_environment_versions
    scripts:
      - name: TESTING
        script: |
          xcode-project run-tests \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_iOS_SCHEME" \
            --device "iPhone 12"
        test_report: build/ios/test/*.xml
